#!/usr/bin/env python3
"""Module generator CLI for Python Backend workflows.

Usage:
    python generate_module.py product --fields name:str sku:str price:decimal stock:int
    python generate_module.py category --fields name:str description:text
    python generate_module.py order --fields user_id:uuid total:decimal status:str

This script generates all Clean Architecture layers:
- Domain (models + schemas)
- Repository
- Service
- API router
- Migration
- Tests
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Literal


# Field type to Python type mapping
TYPE_MAPPING = {
    "str": "str",
    "string": "str",
    "int": "int",
    "integer": "int",
    "float": "float",
    "decimal": "Decimal",
    "bool": "bool",
    "boolean": "bool",
    "datetime": "datetime",
    "date": "date",
    "uuid": "UUID",
    "json": "dict",
    "dict": "dict",
    "list": "list",
}

# Field type to SQLAlchemy type mapping
SQLALCHEMY_TYPE_MAPPING = {
    "str": "String(255)",
    "string": "String(255)",
    "int": "Integer",
    "integer": "Integer",
    "float": "Float",
    "decimal": "Numeric(10, 2)",
    "bool": "Boolean",
    "boolean": "Boolean",
    "datetime": "DateTime(timezone=True)",
    "date": "Date",
    "uuid": "UUID(as_uuid=True)",
    "json": "JSON",
    "dict": "JSON",
    "text": "Text",
}


def parse_fields(fields_str: str) -> list[dict]:
    """Parse fields string into list of field dicts.
    
    Example: "name:str sku:str price:decimal"
    """
    fields = []
    for field in fields_str.split():
        if ":" not in field:
            print(f"Warning: Skipping invalid field '{field}' (expected format: name:type)")
            continue
        
        name, field_type = field.split(":", 1)
        fields.append({
            "name": name.lower(),
            "type": TYPE_MAPPING.get(field_type.lower(), "str"),
            "sqlalchemy_type": SQLALCHEMY_TYPE_MAPPING.get(field_type.lower(), "String(255)"),
            "original_type": field_type.lower(),
        })
    
    return fields


def generate_model(module_name: str, fields: list[dict]) -> str:
    """Generate SQLAlchemy model."""
    field_imports = set()
    field_definitions = []
    
    for field in fields:
        if field["type"] == "Decimal":
            field_imports.add("from sqlalchemy import Numeric")
        elif field["type"] == "UUID":
            field_imports.add("from sqlalchemy.dialects.postgresql import UUID")
        elif field["type"] == "datetime":
            field_imports.add("from sqlalchemy import DateTime")
        elif field["type"] == "date":
            field_imports.add("from sqlalchemy import Date")
        elif field["type"] == "dict":
            field_imports.add("from sqlalchemy import JSON")
        elif field["type"] == "Text":
            field_imports.add("from sqlalchemy import Text")
        
        field_definitions.append(
            f'    {field["name"]}: Mapped[{field["type"]}] = mapped_column(\n'
            f'        {field["sqlalchemy_type"]}, nullable={"False" if field["name"] not in ["description", "status"] else "True"}\n'
            f'    )'
        )
    
    imports = "\n".join(sorted(field_imports))
    fields_code = "\n\n".join(field_definitions)
    
    return f'''"""{module_name.capitalize()} domain model (SQLAlchemy).

Generated by module generator CLI.
"""

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column
{imports}

from app.domain.models.base import BaseModel


class {module_name.capitalize()}(BaseModel):
    """{module_name.capitalize()} database model."""

    __tablename__ = "{module_name}s"

{fields_code}

    def __repr__(self) -> str:
        return f"<{module_name.capitalize()} id={{self.id}}>"
'''


def generate_schemas(module_name: str, fields: list[dict]) -> str:
    """Generate Pydantic schemas."""
    create_fields = []
    update_fields = []
    response_fields = []
    
    for field in fields:
        field_name = field["name"]
        field_type = field["type"]
        
        # Skip ID and timestamps for create/update
        if field_name not in ["id", "created_at", "updated_at", "deleted_at"]:
            if field_type == "str":
                create_fields.append(f'    {field_name}: str')
                update_fields.append(f'    {field_name}: str | None = None')
            elif field_type == "int":
                create_fields.append(f'    {field_name}: int')
                update_fields.append(f'    {field_name}: int | None = None')
            elif field_type == "float":
                create_fields.append(f'    {field_name}: float')
                update_fields.append(f'    {field_name}: float | None = None')
            elif field_type == "Decimal":
                create_fields.append(f'    {field_name}: Decimal')
                update_fields.append(f'    {field_name}: Decimal | None = None')
            elif field_type == "bool":
                create_fields.append(f'    {field_name}: bool')
                update_fields.append(f'    {field_name}: bool | None = None')
            elif field_type == "datetime":
                create_fields.append(f'    {field_name}: datetime')
                update_fields.append(f'    {field_name}: datetime | None = None')
            elif field_type == "UUID":
                create_fields.append(f'    {field_name}: UUID')
                update_fields.append(f'    {field_name}: UUID | None = None')
            else:
                create_fields.append(f'    {field_name}: {field_type}')
                update_fields.append(f'    {field_name}: {field_type} | None = None')
    
    create_schema = "\n".join(create_fields)
    update_schema = "\n".join(update_fields)
    
    return f'''"""{module_name.capitalize()} request/response schemas (Pydantic v2).

Generated by module generator CLI.
"""

import uuid
from datetime import datetime
{'' if 'Decimal' not in [f["type"] for f in fields] else 'from decimal import Decimal'}

from pydantic import BaseModel, ConfigDict, Field

from app.domain.schemas.base import BaseSchema, IDSchema


class {module_name.capitalize()}Create(BaseSchema):
    """Schema for creating a new {module_name}."""

{create_schema}


class {module_name.capitalize()}Update(BaseSchema):
    """Schema for updating a {module_name} (partial)."""

{update_schema}


class {module_name.capitalize()}Response(IDSchema):
    """Schema for {module_name} response."""

{create_schema}


class {module_name.capitalize()}ListResponse(BaseSchema):
    """Paginated list of {module_name}s."""

    items: list[{module_name.capitalize()}Response]
    total: int
    page: int
    limit: int
    total_pages: int
'''


def generate_repository(module_name: str) -> str:
    """Generate repository class."""
    return f'''"""{module_name.capitalize()} repository implementation.

Generated by module generator CLI.
"""

import uuid
from collections.abc import Sequence
from typing import Any

from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.models.{module_name} import {module_name.capitalize()}
from app.repository.base import BaseRepository


class {module_name.capitalize()}Repository(BaseRepository[{module_name.capitalize()}]):
    """Repository for {module_name.capitalize()} entity database operations."""

    def __init__(self, session: AsyncSession) -> None:
        super().__init__({module_name.capitalize()}, session)

    async def get_{module_name}s(
        self,
        *,
        page: int = 1,
        limit: int = 20,
        search: str | None = None,
        sort_by: str = "created_at",
        sort_order: str = "desc",
    ) -> tuple[Sequence[{module_name.capitalize()}], int]:
        """Get paginated {module_name}s with optional search.

        Args:
            page: Page number (1-indexed).
            limit: Items per page.
            search: Optional search term.
            sort_by: Column to sort by.
            sort_order: 'asc' or 'desc'.

        Returns:
            Tuple of (items, total_count).
        """
        filters: list[Any] = []

        if search:
            # Add search logic here based on your fields
            pass

        # Build sort column
        sort_column = getattr({module_name.capitalize()}, sort_by, {module_name.capitalize()}.created_at)
        order = (
            sort_column.asc()
            if sort_order == "asc"
            else sort_column.desc()
        )

        offset = (page - 1) * limit
        return await self.get_all(
            offset=offset,
            limit=limit,
            filters=filters,
            order_by=order,
        )
'''


def generate_service(module_name: str) -> str:
    """Generate service class."""
    return f'''"""{module_name.capitalize()} service (business logic layer).

Generated by module generator CLI.
"""

import math
import uuid

from loguru import logger

from app.core.exceptions import NotFoundException
from app.domain.models.{module_name} import {module_name.capitalize()}
from app.domain.schemas.{module_name} import (
    {module_name.capitalize()}Create,
    {module_name.capitalize()}ListResponse,
    {module_name.capitalize()}Response,
    {module_name.capitalize()}Update,
)
from app.domain.schemas.common import PaginationParams
from app.repository.{module_name}_repository import {module_name.capitalize()}Repository


class {module_name.capitalize()}Service:
    """Handles {module_name} business logic."""

    def __init__(self, repository: {module_name.capitalize()}Repository) -> None:
        self._repo = repository

    async def create_{module_name}(
        self, data: {module_name.capitalize()}Create
    ) -> {module_name.capitalize()}Response:
        """Create a new {module_name}."""
        {module_name} = {module_name.capitalize()}(**data.model_dump())
        created = await self._repo.create({module_name})
        logger.info("{module_name.capitalize()} created", {module_name}_id=str(created.id))
        return {module_name.capitalize()}Response.model_validate(created)

    async def get_{module_name}(
        self, {module_name}_id: uuid.UUID
    ) -> {module_name.capitalize()}Response:
        """Get a single {module_name} by ID.

        Raises:
            NotFoundException: If {module_name} not found.
        """
        {module_name} = await self._repo.get_by_id({module_name}_id)
        if not {module_name}:
            raise NotFoundException("{module_name.capitalize()}", str({module_name}_id))
        return {module_name.capitalize()}Response.model_validate({module_name})

    async def list_{module_name}s(
        self, params: PaginationParams
    ) -> {module_name.capitalize()}ListResponse:
        """List {module_name}s with pagination and search."""
        items, total = await self._repo.get_{module_name}s(
            page=params.page,
            limit=params.limit,
            search=params.search,
            sort_by=params.sort_by,
            sort_order=params.sort_order,
        )

        return {module_name.capitalize()}ListResponse(
            items=[
                {module_name.capitalize()}Response.model_validate(item) for item in items
            ],
            total=total,
            page=params.page,
            limit=params.limit,
            total_pages=math.ceil(total / params.limit),
        )

    async def update_{module_name}(
        self, {module_name}_id: uuid.UUID, data: {module_name.capitalize()}Update
    ) -> {module_name.capitalize()}Response:
        """Update {module_name} fields.

        Raises:
            NotFoundException: If {module_name} not found.
        """
        update_data = data.model_dump(exclude_unset=True)
        if not update_data:
            return await self.get_{module_name}({module_name}_id)

        updated = await self._repo.update_by_id({module_name}_id, update_data)
        if not updated:
            raise NotFoundException("{module_name.capitalize()}", str({module_name}_id))

        logger.info(
            "{module_name.capitalize()} updated",
            {module_name}_id=str({module_name}_id),
            fields=list(update_data.keys()),
        )
        return {module_name.capitalize()}Response.model_validate(updated)

    async def delete_{module_name}(
        self, {module_name}_id: uuid.UUID
    ) -> None:
        """Soft-delete a {module_name}.

        Raises:
            NotFoundException: If {module_name} not found.
        """
        deleted = await self._repo.soft_delete({module_name}_id)
        if not deleted:
            raise NotFoundException("{module_name.capitalize()}", str({module_name}_id))
        logger.info("{module_name.capitalize()} deleted", {module_name}_id=str({module_name}_id))
'''


def generate_router(module_name: str) -> str:
    """Generate API router."""
    return f'''"""{module_name.capitalize()} CRUD API endpoints.

Generated by module generator CLI.
"""

import uuid

from fastapi import APIRouter, Depends, Query, status

from app.api.deps import get_{module_name}_service
from app.domain.schemas.common import MessageResponse, PaginationParams
from app.domain.schemas.{module_name} import (
    {module_name.capitalize()}Create,
    {module_name.capitalize()}ListResponse,
    {module_name.capitalize()}Response,
    {module_name.capitalize()}Update,
)
from app.service.{module_name}_service import {module_name.capitalize()}Service

router = APIRouter(prefix="/{module_name}s", tags=["{module_name.capitalize()}s"])


@router.post(
    "",
    response_model={module_name.capitalize()}Response,
    status_code=status.HTTP_201_CREATED,
)
async def create_{module_name}(
    data: {module_name.capitalize()}Create,
    service: {module_name.capitalize()}Service = Depends(get_{module_name}_service),
) -> {module_name.capitalize()}Response:
    """Create a new {module_name}."""
    return await service.create_{module_name}(data)


@router.get("", response_model={module_name.capitalize()}ListResponse)
async def list_{module_name}s(
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, ge=1, le=100),
    search: str | None = None,
    sort_by: str = "created_at",
    sort_order: str = "desc",
    service: {module_name.capitalize()}Service = Depends(get_{module_name}_service),
) -> {module_name.capitalize()}ListResponse:
    """List {module_name}s with pagination and search."""
    params = PaginationParams(
        page=page,
        limit=limit,
        search=search,
        sort_by=sort_by,
        sort_order=sort_order,
    )
    return await service.list_{module_name}s(params)


@router.get("/{{{module_name}_id}}", response_model={module_name.capitalize()}Response)
async def get_{module_name}(
    {module_name}_id: uuid.UUID,
    service: {module_name.capitalize()}Service = Depends(get_{module_name}_service),
) -> {module_name.capitalize()}Response:
    """Get a {module_name} by ID."""
    return await service.get_{module_name}({module_name}_id)


@router.patch("/{{{module_name}_id}}", response_model={module_name.capitalize()}Response)
async def update_{module_name}(
    {module_name}_id: uuid.UUID,
    data: {module_name.capitalize()}Update,
    service: {module_name.capitalize()}Service = Depends(get_{module_name}_service),
) -> {module_name.capitalize()}Response:
    """Update {module_name} fields (partial update)."""
    return await service.update_{module_name}({module_name}_id, data)


@router.delete(
    "/{{{module_name}_id}}",
    response_model=MessageResponse,
)
async def delete_{module_name}(
    {module_name}_id: uuid.UUID,
    service: {module_name.capitalize()}Service = Depends(get_{module_name}_service),
) -> MessageResponse:
    """Soft-delete a {module_name}."""
    await service.delete_{module_name}({module_name}_id)
    return MessageResponse(message="{module_name.capitalize()} deleted successfully")
'''


def generate_deps(module_name: str) -> str:
    """Generate dependency injection snippet."""
    return f'''
# Add to app/api/deps.py:

def get_{module_name}_repository(
    session: AsyncSession = Depends(get_db),
) -> {module_name.capitalize()}Repository:
    """Provide {module_name.capitalize()}Repository instance."""
    return {module_name.capitalize()}Repository(session)


def get_{module_name}_service(
    repo: {module_name.capitalize()}Repository = Depends(get_{module_name}_repository),
) -> {module_name.capitalize()}Service:
    """Provide {module_name.capitalize()}Service instance."""
    return {module_name.capitalize()}Service(repo)
'''


def generate_migration(module_name: str, fields: list[dict]) -> str:
    """Generate migration file content."""
    columns = []
    for field in fields:
        col_type = field["sqlalchemy_type"]
        nullable = "nullable=True" if field["name"] in ["description", "status"] else "nullable=False"
        columns.append(f'        sa.Column("{field["name"]}", {col_type}, {nullable}),')
    
    columns_code = "\n".join(columns)
    
    migration_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    return f'''"""create {module_name}s table

Revision ID: {migration_id}
Revises: previous_revision
Create Date: {datetime.now().isoformat()}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
{'' if 'UUID' not in [f["type"] for f in fields] else 'from sqlalchemy.dialects.postgresql import UUID'}

# revision identifiers, used by Alembic.
revision: str = '{migration_id}'
down_revision: Union[str, None] = 'previous_revision'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        '{module_name}s',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
{columns_code}
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_{module_name}s_created_at'), '{module_name}s', ['created_at'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_{module_name}s_created_at'), table_name='{module_name}s')
    op.drop_table('{module_name}s')
'''


def generate_test(module_name: str) -> str:
    """Generate test file."""
    return f'''"""Unit tests for {module_name} service.

Generated by module generator CLI.
"""

import pytest
import uuid

from app.domain.schemas.{module_name} import {module_name.capitalize()}Create
from app.service.{module_name}_service import {module_name.capitalize()}Service
from app.repository.{module_name}_repository import {module_name.capitalize()}Repository


@pytest.fixture
def {module_name}_repo(mock_session):
    return {module_name.capitalize()}Repository(mock_session)


@pytest.fixture
def {module_name}_service({module_name}_repo):
    return {module_name.capitalize()}Service({module_name}_repo)


class Test{module_name.capitalize()}Service:
    """Tests for {module_name.capitalize()}Service."""

    @pytest.mark.asyncio
    async def test_create_{module_name}(self, {module_name}_service, mock_session):
        """Test creating a {module_name}."""
        data = {module_name.capitalize()}Create(
            # Add your fields here
        )
        # result = await {module_name}_service.create_{module_name}(data)
        # assert result is not None
        pass

    @pytest.mark.asyncio
    async def test_get_{module_name}(self, {module_name}_service, mock_session):
        """Test getting a {module_name} by ID."""
        # {module_name}_id = uuid.uuid4()
        # result = await {module_name}_service.get_{module_name}({module_name}_id)
        # assert result is not None
        pass
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate Clean Architecture module for FastAPI backend"
    )
    parser.add_argument(
        "module_name",
        help="Name of the module (e.g., product, category, order)"
    )
    parser.add_argument(
        "--fields",
        required=True,
        help="Fields in format: 'name:str sku:str price:decimal stock:int'"
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory (default: current directory)"
    )
    
    args = parser.parse_args()
    
    module_name = args.module_name.lower().replace("-", "_")
    fields = parse_fields(args.fields)
    
    if not fields:
        print("Error: No valid fields provided")
        sys.exit(1)
    
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate files
    files = {
        f"app/domain/models/{module_name}.py": generate_model(module_name, fields),
        f"app/domain/schemas/{module_name}.py": generate_schemas(module_name, fields),
        f"app/repository/{module_name}_repository.py": generate_repository(module_name),
        f"app/service/{module_name}_service.py": generate_service(module_name),
        f"app/api/v1/{module_name}_router.py": generate_router(module_name),
        f"tests/unit/test_{module_name}_service.py": generate_test(module_name),
        f"migrations/versions/{datetime.now().strftime('%Y%m%d_%H%M%S')}_create_{module_name}s_table.py": generate_migration(module_name, fields),
    }
    
    print(f"\n🔧 Generating module: {module_name}")
    print(f"📁 Fields: {', '.join([f['name'] + ':' + f['type'] for f in fields])}")
    print()
    
    for filepath, content in files.items():
        file_path = output_dir / filepath
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content)
        print(f"✅ Created: {filepath}")
    
    # Print dependency injection snippet
    print("\n" + "=" * 60)
    print("📝 Add to app/api/deps.py:")
    print("=" * 60)
    print(generate_deps(module_name))
    
    print("\n" + "=" * 60)
    print("📝 Add to app/api/v1/router.py:")
    print("=" * 60)
    print(f"from app.api.v1.{module_name}_router import router as {module_name}_router")
    print(f"api_v1_router.include_router({module_name}_router)")
    
    print("\n" + "=" * 60)
    print("📝 Next steps:")
    print("=" * 60)
    print("1. Review and edit the generated files")
    print("2. Add the dependency injection to app/api/deps.py")
    print("3. Register the router in app/api/v1/router.py")
    print("4. Create and run the migration:")
    print(f"   make migrate-create msg=\"create {module_name}s_table\"")
    print("   make migrate-up")
    print("5. Write tests and run:")
    print("   pytest tests/unit/test_{module_name}_service.py")
    print()


if __name__ == "__main__":
    main()
